### ISSUE TITLE
Erro ao rodar as migrações

### ISSUE THREAD

**Issue by taciogt** [carlosmaniero/docker-spa#1]
Oi @carlosmaniero,

Fui avaliar seu projeto enviado como solução para o teste de backend do Viva Decora e não consegui rodar aplicação.
Ao executar o comando 
`$ docker-compose run rest_app python3 manage.py loaddata initial_data`
Foi lançado o erro:

```
Creating dockerspa_elasticsearch_test_1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: could not connect to server: Connection refused
    Is the server running on host "postgres_host" (172.17.0.2) and accepting
    TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 59, in handle
    with transaction.atomic(using=self.using):
  File "/usr/local/lib/python3.5/site-packages/django/db/transaction.py", line 158, in __enter__
    if not connection.get_autocommit():
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 365, in get_autocommit
    self.ensure_connection()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: could not connect to server: Connection refused
    Is the server running on host "postgres_host" (172.17.0.2) and accepting
    TCP/IP connections on port 5432?
```

E ao executar o comando 
`$ docker-compose up`
Foi lançado o erro:

```
Creating dockerspa_nginx_1

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint dockerspa_nginx_1 (53f5c0db0c464f0b9f0231b1d035b5cb250637aa74e644fc6b25aa1ef26987f4): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
ERROR: Encountered errors while bringing up the project.
```

Estou tentando executar o projeto sobre um Mac OSX El Capitan e versão do docker 1.12.0-beta21

**Comment by carlosmaniero** [comment]
@taciogt, Cara que estranho. Como eu rodo tudo via docker, eu não uso as portas do meu host. Então as seguintes portas devem estar disponíveis:
- 80
- 9200
- 8081

Se você estiver rodando um apache ou um ngnix local, ou qualquer coisa que usa a porta 80 o docker vai dar esse erro `EADDRINUSE`, porque a porta já está em uso.

Em relação à rodar os `loaddata`, é bem estranho, aparentemente, o banco de dados também não subiu. 
Faz o seguinte, executa o `docker-compose up`, espera a aplicação subir e em um outro console você executa o loaddata, assim é certeza que o banco de dados estará rodando.

**Comment by carlosmaniero** [comment]
Qualquer coisa, me avisa que eu troco a porta da aplicação.

**Comment by carlosmaniero** [comment]
Mas acredito que é só você dar um stop no seu ngnix ou apache local que já resolve.

**Comment by carlosmaniero** [comment]
Resolvido trocando a porta do projeto.
